replicaCount: 1
nameOverride: ""
fullnameOverride: ""
serviceName: 'invoice-customer'
serviceVersion: '2.1.1'
serviceDescription: 'Send the customer an invoice for the items ordered'
serviceType: 'NATIVE'
serviceLogLevel: INFO
image:
  name: 'invoice-customer'
  tag: '2.1.1'
  pullPolicy: Always
imageCredentials:
  secretName: ""
ace:
  sidecar:
    brokerHost: ace-runtime-services-kafka
    brokerPort: 9092
    executiveHost: ace-runtime-services-executive
    executivePort: 9001
  jaeger:
    enabled: true
    collector:
      host: ace-jaeger-collector
      port: 14267
  image:
    repository: axway-docker-public-registry.bintray.io/ace
    tag: 0.0.8
    pullPolicy: Always
  imageCredentials:
    secretName: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
