replicaCount: 1
nameOverride: ""
fullnameOverride: ""
serviceName: 'item-id-aggregation'
serviceVersion: '0.0.2'
serviceDescription: 'Aggregate the incoming orders by Item ID'
serviceType: 'AGGREGATION'
serviceLogLevel: INFO
image:
  name: 'item-id-aggregation'
  tag: '0.0.2'
  pullPolicy: Always
imageCredentials:
  secretName: ""
ace:
  sidecar:
    brokerHost: ace-runtime-services-kafka
    brokerPort: 9092
    executiveHost: ace-runtime-services-executive
    executivePort: 9001
  jaeger:
    enabled: true
    collector:
      host: ace-jaeger-collector
      port: 14267
  image:
    repository: axway-docker-public-registry.bintray.io/ace
    tag: 0.0.8
    pullPolicy: Always
  imageCredentials:
    secretName: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
